# Generated by Django 3.1.1 on 2020-09-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferias',
            name='justificativa',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
