# Generated by Django 3.1.1 on 2020-09-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedBack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='responsave',
            new_name='responsavel',
        ),
    ]
