# Generated by Django 3.1.1 on 2020-09-16 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedBack', '0002_auto_20200916_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='responsavel',
            new_name='responsavelbas',
        ),
    ]
