# Generated by Django 3.1.1 on 2020-09-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedBack', '0005_feedback_usuarioid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
