# Generated by Django 3.1.1 on 2020-09-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedBack', '0004_auto_20200916_1916'),
        ('usuario', '0003_auto_20200917_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='feedBack',
            field=models.ManyToManyField(to='feedBack.Feedback'),
        ),
    ]
