# Generated by Django 3.1.1 on 2020-09-24 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
        ('usuario', '0004_usuario_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='funcaoFuncionarioId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.cargo'),
        ),
    ]
