# Generated by Django 3.1.1 on 2020-09-24 05:40

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
        ('usuario', '0005_auto_20200924_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='funcaoFuncionarioId',
            field=models.ForeignKey(on_delete=django.db.models.fields.related.ForeignObject, to='cargo.cargo'),
        ),
    ]
