# Generated by Django 3.1.1 on 2020-09-24 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
        ('usuario', '0006_auto_20200924_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='funcaoFuncionarioId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.cargo'),
        ),
    ]
