# Generated by Django 3.1.1 on 2020-09-24 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
        ('usuario', '0007_auto_20200924_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='departamentoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento'),
        ),
    ]
