# Generated by Django 3.1.1 on 2020-09-24 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_remove_usuario_isativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='feedBack',
        ),
    ]
