# Generated by Django 3.1.1 on 2020-09-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_remove_usuario_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dataDeTermino',
            field=models.DateField(null=True),
        ),
    ]
