# Generated by Django 3.1.1 on 2020-09-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketstatus', '0003_auto_20200917_0448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketstatus',
            old_name='estatus',
            new_name='status',
        ),
    ]
