# Generated by Django 3.1.1 on 2020-09-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ausencia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ausencia',
            old_name='usuarioId',
            new_name='funcionarioId',
        ),
    ]
