# Generated by Django 3.1.1 on 2020-09-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_tickets_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='assunto',
            field=models.TextField(default=1, max_length=140),
            preserve_default=False,
        ),
    ]
