# Generated by Django 3.1.1 on 2020-09-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20200917_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='dataCriacao',
            field=models.DateField(default=1),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='dataFim',
            field=models.DateField(default=1),
        ),
    ]
